### PR TITLE
Fix CT download

### PR DESCRIPTION
**Pull request by vanekjar**

### CODE REVIEW

**Comment by peci1** [comment]
Thanks for fixing the https protocol... However, the other change won't probably work - the result of your approach is kilometers long commandline, which especially windows won't like (tested now on my machine). That's why I'm using the download list. Do you run tv-dl on linux?

**Comment by vanekjar** [comment]
Good point. I wasn't testing it on Windows. Running on Linux worked fine for me.
But I agree with you. Reverting the last commit.

**Comment by peci1** [comment]
Windows is really holding a lot of things back, but I'd like to keep it compatible.

`--show-progress` is a relatively new option to wget, not everybody has it (e.g. my Trusty computer has 1.15, but `--show-progress` is since 1.16). But there's a way to detect that: https://stackoverflow.com/a/32491843/1076564 . Could you incorporate that into this PR?

**Comment by peci1** [comment]
Don't you get certificate validation errors now when downloading? I do both on Linux and Windows, even without your PR (just with the change to https). It seems with the new distribution company O2, they have a bit misconfigured servers and do not include intermediate certs in their server certs, which is a problem for wget (the intermediate is not in /etc/ssl/certs), but is ok for Firefox (it is in its cert store). https://www.sslshopper.com/ssl-checker.html#hostname=ivys-st03-2.o2tv.cz . I'll try to raise an issue with them, but I'd like to hear from you if you have the same problem...

**Comment by vanekjar** [comment]
You're right. The backward compatibility with `wget` could be an issue. I decided to ditch the whole wget modification for the sake of compatibility. I don't think it is worth it to add another dependency on `grep` binary – that could be another potential issue on Windows.

**Comment by vanekjar** [comment]
Regarding the TLS. Yes, I had the same problem. I actually imported the Thawte certificate locally as a workaround. Not sure if this is an issue that should be solved in the `tv-dl` code. It is more about the environment configuration.

I was thinking for a while that we could bundle the CA certificate with the code. But today I see the intermediate certificate changed. Today the download doesn't work anymore. So I am a little lost in the mess they made.

Before I had to import:
Thawte SHA256 SSL CA
36 34 9e 18 c9 9c 26 69 b6 56 2e 6c e5 ad 71 32

Today it is:
Thawte RSA CA 2018 
02 5a 8a ef 19 6f 7e 0d 6c 21 04 b2 1a e6 70 2b

**Comment by vanekjar** [comment]
I have given up on trying to fix the certificate issue. I have added an optional argument to disable the SSL certificate validation instead. Let me know what you think.

**Comment by peci1** [comment]
Perfect, I had exactly the same idea. Thanks very much!

**Comment by peci1** [comment]
I polished the code a little bit more and completely removed wget dependency - now it uses the Python libraries everywhere... 

You can check it out, I hope it does what you wanted - a clean progressbar... I just moved the development to master branch, so don't forget to switch.

**Pull request merged**
